---
version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.7.8-management
        container_name: rabbitmqpluralsight
        hostname : rabbitmqpluralsighthost
        depends_on:
          - mysqldb          
        environment:        
          - hostname=rabbitmqpluralsighthostenv
          - RABBITMQ_DEFAULT_USER=psuser
          - RABBITMQ_DEFAULT_PASS=pspass
          - RABBITMQ_DEFAULT_VHOST=rabbitmqpluralsighthosthost
        ports :
          - 15672:15672
          - 5672:5672
             
    mysqldb:    
        image: mysql/mysql-server
        container_name: mysqlpluralsight
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=ilovebnhp
          - AAMYSQL_RANDOM_ROOT_PASSWORD=yes
          - MYSQL_USER=psuser
          - MYSQL_DATABASE=tasklogs
          - MYSQL_PASSWORD=pspass
          - MYSQL_LOG_CONSOLE=true          
          
        ports :
          - 3306:3306  
          
          
